[source]
url = "wss://rpc.polkadot.io"

[output]
format = "json"

[tcp]
maxsourcequeue = 10485760 # 10MB in bytes

[nats]
maxsourcequeue = 10485760 # 10MB in bytes

[pubsub]
servers = ["nats://nats:4222"]
