apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-sourcing
  namespace: subdot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-sourcing
  template:
    metadata:
      labels:
        app: event-sourcing
    spec:
      containers:
        - name: event-sourcing
          image: orbitalstate/subdot:latest
          args:
            - "filter"
            - "--source"
            - "smoldot.wss://rpc.polkadot.io"
            - "--query"
            - "true"
            - "--target"
            - "nats://nats.subdot.svc.cluster.local:4222/polkadot.events"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"