apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-log
  namespace: subdot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-log
  template:
    metadata:
      labels:
        app: notification-log
    spec:
      containers:
        - name: notification-log
          image: natsio/nats-box:latest
          command: ["nats", "sub", "notification.>", "--ack"]
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: NATS_URL
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"