apiVersion: apps/v1
kind: Deployment
metadata:
  name: subdot-worker
  namespace: subdot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subdot-worker
  template:
    metadata:
      labels:
        app: subdot-worker
    spec:
      containers:
        - name: subdot-worker
          image: orbitalstate/subdot:latest
          args: ["worker", "--config", "/app/subdot.toml"]
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: NATS_URL
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"